### ISSUE TITLE
Documentation - fix maintainers list in SQL

### ISSUE THREAD

**Issue by YANG-DB** [opensearch-project/sql-odbc#29]
**What is the bug?**
Correlation of all SQL related maintainers document

**How can one reproduce the bug?**
N/A

**What is the expected behavior?**
By in sync across all SQL repos

**What is your host/environment?**
All

**Do you have any screenshots?**
see

https://github.com/opensearch-project/sql-odbc/blob/main/MAINTAINERS.md

**Do you have any additional context?**
Add any other context about the problem.

**Comment by Yury-Fridlyand** [comment]
Fixed by #51 and #40
