### ISSUE TITLE
[BUG] Fix Failing `linkchecker` Job

### ISSUE THREAD

**Issue by currantw** [opensearch-project/sql-odbc#78]
**What is the bug?**

Failing `linkchecker` pipeline job.

**How can one reproduce the bug?**

Run pipeline.

**What is the expected behavior?**

Pipeline job should pass.

**What is your host/environment?**

N/A. GitHub pipeline issue.

**Do you have any screenshots?**

Job output:

<img width="1222" alt="image" src="https://github.com/user-attachments/assets/781a42fe-34fd-4980-acbb-7e79ecb5ca9d">

**Do you have any additional context?**

See also https://github.com/opensearch-project/sql-odbc/issues/74

**Comment by currantw** [comment]
This job runs `lychee`, which checks for broken links in Markdown files. Resolving this issue should just be a matter of going through the 8 documents listed above and fixed/removed all of the broken links.

**Comment by YANG-DB** [comment]
closing this after [fixed](https://github.com/opensearch-project/sql-odbc/pull/81)
